  <h2>Site Error</h2>
  <p>An error was encountered while publishing this resource.
  </p>
  <p><strong>IndexError</strong></p>

  Sorry, a site error occurred.<p><p>Traceback (innermost last):
<ul>

<li>  Module ZPublisher.Publish, line 196, in publish_module_standard</li>

<li>  Module Products.PlacelessTranslationService.PatchStringIO, line 34, in new_publish</li>

<li>  Module ZPublisher.Publish, line 146, in publish</li>

<li>  Module Zope2.App.startup, line 222, in zpublisher_exception_hook</li>

<li>  Module ZPublisher.Publish, line 106, in publish</li>

<li>  Module ZPublisher.BaseRequest, line 279, in traverse</li>

<li>  Module Products.CMFPlone.FactoryTool, line 321, in __before_publishing_traverse__</li>

</ul>IndexError: list index out of range (Also, the following error occurred while attempting to render the standard error message, please see the event log for full details: @@plone)
</p></p>
  <hr noshade="noshade"/>

  <p>Troubleshooting Suggestions</p>

  <ul>
  <li>The URL may be incorrect.</li>
  <li>The parameters passed to this resource may be incorrect.</li>
  <li>A resource that this resource relies on may be
      encountering an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>